/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteRouteImport } from './routes/landing/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LandingTenantSlugRouteImport } from './routes/landing/$tenantSlug'
import { Route as DashboardTenantsRouteImport } from './routes/dashboard/tenants'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardGlobalStateRouteImport } from './routes/dashboard/global-state'
import { Route as DashboardFormsRouteImport } from './routes/dashboard/forms'
import { Route as DashboardDataRouteImport } from './routes/dashboard/data'
import { Route as DashboardTenantRouteRouteImport } from './routes/dashboard/tenant/route'
import { Route as DashboardLandingPagesRouteRouteImport } from './routes/dashboard/landing-pages/route'
import { Route as DashboardLandingPagesIndexRouteImport } from './routes/dashboard/landing-pages/index'
import { Route as DashboardAuditLogsIndexRouteImport } from './routes/dashboard/audit-logs/index'
import { Route as DashboardOntractSignDoctorContractIdRouteImport } from './routes/dashboard/ontract-sign-doctor.$contractId'
import { Route as DashboardLandingPagesPageIdRouteImport } from './routes/dashboard/landing-pages/$pageId'
import { Route as DashboardTenantSettingsRouteRouteImport } from './routes/dashboard/tenant/settings/route'
import { Route as DashboardTenantProductsRouteRouteImport } from './routes/dashboard/tenant/products/route'
import { Route as DashboardTenantPlansRouteRouteImport } from './routes/dashboard/tenant/plans/route'
import { Route as DashboardTenantDoctorsRouteRouteImport } from './routes/dashboard/tenant/doctors/route'
import { Route as DashboardTenantDepartmentsServicesRouteRouteImport } from './routes/dashboard/tenant/departments-services/route'
import { Route as DashboardTenantContractsRouteRouteImport } from './routes/dashboard/tenant/contracts/route'
import { Route as DashboardTenantContractsIndexRouteImport } from './routes/dashboard/tenant/contracts/index'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LandingTenantSlugRoute = LandingTenantSlugRouteImport.update({
  id: '/$tenantSlug',
  path: '/$tenantSlug',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DashboardTenantsRoute = DashboardTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGlobalStateRoute = DashboardGlobalStateRouteImport.update({
  id: '/global-state',
  path: '/global-state',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFormsRoute = DashboardFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDataRoute = DashboardDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTenantRouteRoute = DashboardTenantRouteRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLandingPagesRouteRoute =
  DashboardLandingPagesRouteRouteImport.update({
    id: '/landing-pages',
    path: '/landing-pages',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLandingPagesIndexRoute =
  DashboardLandingPagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLandingPagesRouteRoute,
  } as any)
const DashboardAuditLogsIndexRoute = DashboardAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOntractSignDoctorContractIdRoute =
  DashboardOntractSignDoctorContractIdRouteImport.update({
    id: '/ontract-sign-doctor/$contractId',
    path: '/ontract-sign-doctor/$contractId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLandingPagesPageIdRoute =
  DashboardLandingPagesPageIdRouteImport.update({
    id: '/$pageId',
    path: '/$pageId',
    getParentRoute: () => DashboardLandingPagesRouteRoute,
  } as any)
const DashboardTenantSettingsRouteRoute =
  DashboardTenantSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardTenantRouteRoute,
  } as any)
const DashboardTenantProductsRouteRoute =
  DashboardTenantProductsRouteRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => DashboardTenantRouteRoute,
  } as any)
const DashboardTenantPlansRouteRoute =
  DashboardTenantPlansRouteRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => DashboardTenantRouteRoute,
  } as any)
const DashboardTenantDoctorsRouteRoute =
  DashboardTenantDoctorsRouteRouteImport.update({
    id: '/doctors',
    path: '/doctors',
    getParentRoute: () => DashboardTenantRouteRoute,
  } as any)
const DashboardTenantDepartmentsServicesRouteRoute =
  DashboardTenantDepartmentsServicesRouteRouteImport.update({
    id: '/departments-services',
    path: '/departments-services',
    getParentRoute: () => DashboardTenantRouteRoute,
  } as any)
const DashboardTenantContractsRouteRoute =
  DashboardTenantContractsRouteRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => DashboardTenantRouteRoute,
  } as any)
const DashboardTenantContractsIndexRoute =
  DashboardTenantContractsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTenantContractsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/landing': typeof LandingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tenants': typeof TenantsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/landing-pages': typeof DashboardLandingPagesRouteRouteWithChildren
  '/dashboard/tenant': typeof DashboardTenantRouteRouteWithChildren
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/forms': typeof DashboardFormsRoute
  '/dashboard/global-state': typeof DashboardGlobalStateRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/landing/$tenantSlug': typeof LandingTenantSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tenant/contracts': typeof DashboardTenantContractsRouteRouteWithChildren
  '/dashboard/tenant/departments-services': typeof DashboardTenantDepartmentsServicesRouteRoute
  '/dashboard/tenant/doctors': typeof DashboardTenantDoctorsRouteRoute
  '/dashboard/tenant/plans': typeof DashboardTenantPlansRouteRoute
  '/dashboard/tenant/products': typeof DashboardTenantProductsRouteRoute
  '/dashboard/tenant/settings': typeof DashboardTenantSettingsRouteRoute
  '/dashboard/landing-pages/$pageId': typeof DashboardLandingPagesPageIdRoute
  '/dashboard/ontract-sign-doctor/$contractId': typeof DashboardOntractSignDoctorContractIdRoute
  '/dashboard/audit-logs/': typeof DashboardAuditLogsIndexRoute
  '/dashboard/landing-pages/': typeof DashboardLandingPagesIndexRoute
  '/dashboard/tenant/contracts/': typeof DashboardTenantContractsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tenants': typeof TenantsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/tenant': typeof DashboardTenantRouteRouteWithChildren
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/forms': typeof DashboardFormsRoute
  '/dashboard/global-state': typeof DashboardGlobalStateRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/landing/$tenantSlug': typeof LandingTenantSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/tenant/departments-services': typeof DashboardTenantDepartmentsServicesRouteRoute
  '/dashboard/tenant/doctors': typeof DashboardTenantDoctorsRouteRoute
  '/dashboard/tenant/plans': typeof DashboardTenantPlansRouteRoute
  '/dashboard/tenant/products': typeof DashboardTenantProductsRouteRoute
  '/dashboard/tenant/settings': typeof DashboardTenantSettingsRouteRoute
  '/dashboard/landing-pages/$pageId': typeof DashboardLandingPagesPageIdRoute
  '/dashboard/ontract-sign-doctor/$contractId': typeof DashboardOntractSignDoctorContractIdRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsIndexRoute
  '/dashboard/landing-pages': typeof DashboardLandingPagesIndexRoute
  '/dashboard/tenant/contracts': typeof DashboardTenantContractsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/landing': typeof LandingRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tenants': typeof TenantsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/landing-pages': typeof DashboardLandingPagesRouteRouteWithChildren
  '/dashboard/tenant': typeof DashboardTenantRouteRouteWithChildren
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/forms': typeof DashboardFormsRoute
  '/dashboard/global-state': typeof DashboardGlobalStateRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/landing/$tenantSlug': typeof LandingTenantSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tenant/contracts': typeof DashboardTenantContractsRouteRouteWithChildren
  '/dashboard/tenant/departments-services': typeof DashboardTenantDepartmentsServicesRouteRoute
  '/dashboard/tenant/doctors': typeof DashboardTenantDoctorsRouteRoute
  '/dashboard/tenant/plans': typeof DashboardTenantPlansRouteRoute
  '/dashboard/tenant/products': typeof DashboardTenantProductsRouteRoute
  '/dashboard/tenant/settings': typeof DashboardTenantSettingsRouteRoute
  '/dashboard/landing-pages/$pageId': typeof DashboardLandingPagesPageIdRoute
  '/dashboard/ontract-sign-doctor/$contractId': typeof DashboardOntractSignDoctorContractIdRoute
  '/dashboard/audit-logs/': typeof DashboardAuditLogsIndexRoute
  '/dashboard/landing-pages/': typeof DashboardLandingPagesIndexRoute
  '/dashboard/tenant/contracts/': typeof DashboardTenantContractsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/register'
    | '/tenants'
    | '/unauthorized'
    | '/dashboard/landing-pages'
    | '/dashboard/tenant'
    | '/dashboard/data'
    | '/dashboard/forms'
    | '/dashboard/global-state'
    | '/dashboard/roles'
    | '/dashboard/tenants'
    | '/landing/$tenantSlug'
    | '/dashboard/'
    | '/dashboard/tenant/contracts'
    | '/dashboard/tenant/departments-services'
    | '/dashboard/tenant/doctors'
    | '/dashboard/tenant/plans'
    | '/dashboard/tenant/products'
    | '/dashboard/tenant/settings'
    | '/dashboard/landing-pages/$pageId'
    | '/dashboard/ontract-sign-doctor/$contractId'
    | '/dashboard/audit-logs/'
    | '/dashboard/landing-pages/'
    | '/dashboard/tenant/contracts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/register'
    | '/tenants'
    | '/unauthorized'
    | '/dashboard/tenant'
    | '/dashboard/data'
    | '/dashboard/forms'
    | '/dashboard/global-state'
    | '/dashboard/roles'
    | '/dashboard/tenants'
    | '/landing/$tenantSlug'
    | '/dashboard'
    | '/dashboard/tenant/departments-services'
    | '/dashboard/tenant/doctors'
    | '/dashboard/tenant/plans'
    | '/dashboard/tenant/products'
    | '/dashboard/tenant/settings'
    | '/dashboard/landing-pages/$pageId'
    | '/dashboard/ontract-sign-doctor/$contractId'
    | '/dashboard/audit-logs'
    | '/dashboard/landing-pages'
    | '/dashboard/tenant/contracts'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/landing'
    | '/login'
    | '/register'
    | '/tenants'
    | '/unauthorized'
    | '/dashboard/landing-pages'
    | '/dashboard/tenant'
    | '/dashboard/data'
    | '/dashboard/forms'
    | '/dashboard/global-state'
    | '/dashboard/roles'
    | '/dashboard/tenants'
    | '/landing/$tenantSlug'
    | '/dashboard/'
    | '/dashboard/tenant/contracts'
    | '/dashboard/tenant/departments-services'
    | '/dashboard/tenant/doctors'
    | '/dashboard/tenant/plans'
    | '/dashboard/tenant/products'
    | '/dashboard/tenant/settings'
    | '/dashboard/landing-pages/$pageId'
    | '/dashboard/ontract-sign-doctor/$contractId'
    | '/dashboard/audit-logs/'
    | '/dashboard/landing-pages/'
    | '/dashboard/tenant/contracts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TenantsRoute: typeof TenantsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/landing/$tenantSlug': {
      id: '/landing/$tenantSlug'
      path: '/$tenantSlug'
      fullPath: '/landing/$tenantSlug'
      preLoaderRoute: typeof LandingTenantSlugRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/dashboard/tenants': {
      id: '/dashboard/tenants'
      path: '/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/global-state': {
      id: '/dashboard/global-state'
      path: '/global-state'
      fullPath: '/dashboard/global-state'
      preLoaderRoute: typeof DashboardGlobalStateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/forms': {
      id: '/dashboard/forms'
      path: '/forms'
      fullPath: '/dashboard/forms'
      preLoaderRoute: typeof DashboardFormsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/data': {
      id: '/dashboard/data'
      path: '/data'
      fullPath: '/dashboard/data'
      preLoaderRoute: typeof DashboardDataRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/landing-pages': {
      id: '/dashboard/landing-pages'
      path: '/landing-pages'
      fullPath: '/dashboard/landing-pages'
      preLoaderRoute: typeof DashboardLandingPagesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/landing-pages/': {
      id: '/dashboard/landing-pages/'
      path: '/'
      fullPath: '/dashboard/landing-pages/'
      preLoaderRoute: typeof DashboardLandingPagesIndexRouteImport
      parentRoute: typeof DashboardLandingPagesRouteRoute
    }
    '/dashboard/audit-logs/': {
      id: '/dashboard/audit-logs/'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs/'
      preLoaderRoute: typeof DashboardAuditLogsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ontract-sign-doctor/$contractId': {
      id: '/dashboard/ontract-sign-doctor/$contractId'
      path: '/ontract-sign-doctor/$contractId'
      fullPath: '/dashboard/ontract-sign-doctor/$contractId'
      preLoaderRoute: typeof DashboardOntractSignDoctorContractIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/landing-pages/$pageId': {
      id: '/dashboard/landing-pages/$pageId'
      path: '/$pageId'
      fullPath: '/dashboard/landing-pages/$pageId'
      preLoaderRoute: typeof DashboardLandingPagesPageIdRouteImport
      parentRoute: typeof DashboardLandingPagesRouteRoute
    }
    '/dashboard/tenant/settings': {
      id: '/dashboard/tenant/settings'
      path: '/settings'
      fullPath: '/dashboard/tenant/settings'
      preLoaderRoute: typeof DashboardTenantSettingsRouteRouteImport
      parentRoute: typeof DashboardTenantRouteRoute
    }
    '/dashboard/tenant/products': {
      id: '/dashboard/tenant/products'
      path: '/products'
      fullPath: '/dashboard/tenant/products'
      preLoaderRoute: typeof DashboardTenantProductsRouteRouteImport
      parentRoute: typeof DashboardTenantRouteRoute
    }
    '/dashboard/tenant/plans': {
      id: '/dashboard/tenant/plans'
      path: '/plans'
      fullPath: '/dashboard/tenant/plans'
      preLoaderRoute: typeof DashboardTenantPlansRouteRouteImport
      parentRoute: typeof DashboardTenantRouteRoute
    }
    '/dashboard/tenant/doctors': {
      id: '/dashboard/tenant/doctors'
      path: '/doctors'
      fullPath: '/dashboard/tenant/doctors'
      preLoaderRoute: typeof DashboardTenantDoctorsRouteRouteImport
      parentRoute: typeof DashboardTenantRouteRoute
    }
    '/dashboard/tenant/departments-services': {
      id: '/dashboard/tenant/departments-services'
      path: '/departments-services'
      fullPath: '/dashboard/tenant/departments-services'
      preLoaderRoute: typeof DashboardTenantDepartmentsServicesRouteRouteImport
      parentRoute: typeof DashboardTenantRouteRoute
    }
    '/dashboard/tenant/contracts': {
      id: '/dashboard/tenant/contracts'
      path: '/contracts'
      fullPath: '/dashboard/tenant/contracts'
      preLoaderRoute: typeof DashboardTenantContractsRouteRouteImport
      parentRoute: typeof DashboardTenantRouteRoute
    }
    '/dashboard/tenant/contracts/': {
      id: '/dashboard/tenant/contracts/'
      path: '/'
      fullPath: '/dashboard/tenant/contracts/'
      preLoaderRoute: typeof DashboardTenantContractsIndexRouteImport
      parentRoute: typeof DashboardTenantContractsRouteRoute
    }
  }
}

interface DashboardLandingPagesRouteRouteChildren {
  DashboardLandingPagesPageIdRoute: typeof DashboardLandingPagesPageIdRoute
  DashboardLandingPagesIndexRoute: typeof DashboardLandingPagesIndexRoute
}

const DashboardLandingPagesRouteRouteChildren: DashboardLandingPagesRouteRouteChildren =
  {
    DashboardLandingPagesPageIdRoute: DashboardLandingPagesPageIdRoute,
    DashboardLandingPagesIndexRoute: DashboardLandingPagesIndexRoute,
  }

const DashboardLandingPagesRouteRouteWithChildren =
  DashboardLandingPagesRouteRoute._addFileChildren(
    DashboardLandingPagesRouteRouteChildren,
  )

interface DashboardTenantContractsRouteRouteChildren {
  DashboardTenantContractsIndexRoute: typeof DashboardTenantContractsIndexRoute
}

const DashboardTenantContractsRouteRouteChildren: DashboardTenantContractsRouteRouteChildren =
  {
    DashboardTenantContractsIndexRoute: DashboardTenantContractsIndexRoute,
  }

const DashboardTenantContractsRouteRouteWithChildren =
  DashboardTenantContractsRouteRoute._addFileChildren(
    DashboardTenantContractsRouteRouteChildren,
  )

interface DashboardTenantRouteRouteChildren {
  DashboardTenantContractsRouteRoute: typeof DashboardTenantContractsRouteRouteWithChildren
  DashboardTenantDepartmentsServicesRouteRoute: typeof DashboardTenantDepartmentsServicesRouteRoute
  DashboardTenantDoctorsRouteRoute: typeof DashboardTenantDoctorsRouteRoute
  DashboardTenantPlansRouteRoute: typeof DashboardTenantPlansRouteRoute
  DashboardTenantProductsRouteRoute: typeof DashboardTenantProductsRouteRoute
  DashboardTenantSettingsRouteRoute: typeof DashboardTenantSettingsRouteRoute
}

const DashboardTenantRouteRouteChildren: DashboardTenantRouteRouteChildren = {
  DashboardTenantContractsRouteRoute:
    DashboardTenantContractsRouteRouteWithChildren,
  DashboardTenantDepartmentsServicesRouteRoute:
    DashboardTenantDepartmentsServicesRouteRoute,
  DashboardTenantDoctorsRouteRoute: DashboardTenantDoctorsRouteRoute,
  DashboardTenantPlansRouteRoute: DashboardTenantPlansRouteRoute,
  DashboardTenantProductsRouteRoute: DashboardTenantProductsRouteRoute,
  DashboardTenantSettingsRouteRoute: DashboardTenantSettingsRouteRoute,
}

const DashboardTenantRouteRouteWithChildren =
  DashboardTenantRouteRoute._addFileChildren(DashboardTenantRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardLandingPagesRouteRoute: typeof DashboardLandingPagesRouteRouteWithChildren
  DashboardTenantRouteRoute: typeof DashboardTenantRouteRouteWithChildren
  DashboardDataRoute: typeof DashboardDataRoute
  DashboardFormsRoute: typeof DashboardFormsRoute
  DashboardGlobalStateRoute: typeof DashboardGlobalStateRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardTenantsRoute: typeof DashboardTenantsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOntractSignDoctorContractIdRoute: typeof DashboardOntractSignDoctorContractIdRoute
  DashboardAuditLogsIndexRoute: typeof DashboardAuditLogsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLandingPagesRouteRoute: DashboardLandingPagesRouteRouteWithChildren,
  DashboardTenantRouteRoute: DashboardTenantRouteRouteWithChildren,
  DashboardDataRoute: DashboardDataRoute,
  DashboardFormsRoute: DashboardFormsRoute,
  DashboardGlobalStateRoute: DashboardGlobalStateRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardTenantsRoute: DashboardTenantsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOntractSignDoctorContractIdRoute:
    DashboardOntractSignDoctorContractIdRoute,
  DashboardAuditLogsIndexRoute: DashboardAuditLogsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingTenantSlugRoute: typeof LandingTenantSlugRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingTenantSlugRoute: LandingTenantSlugRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TenantsRoute: TenantsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
