/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnrollmentRouteImport } from './routes/enrollment'
import { Route as ContactAdminRouteImport } from './routes/contact-admin'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor/appointments'
import { Route as DashboardTenantsRouteImport } from './routes/dashboard/tenants'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardGlobalStateRouteImport } from './routes/dashboard/global-state'
import { Route as DashboardFormsRouteImport } from './routes/dashboard/forms'
import { Route as DashboardDialogRouteImport } from './routes/dashboard/dialog'
import { Route as DashboardDataRouteImport } from './routes/dashboard/data'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard/appointments'
import { Route as AppointmentsSelectTenantRouteImport } from './routes/appointments/select-tenant'
import { Route as AppointmentsMyRouteImport } from './routes/appointments/my'
import { Route as AppointmentsConfirmationRouteImport } from './routes/appointments/confirmation'
import { Route as AppointmentsBookRouteImport } from './routes/appointments/book'
import { Route as AppointmentsAppointmentIdRouteImport } from './routes/appointments/$appointmentId'
import { Route as DashboardLandingPagesRouteRouteImport } from './routes/dashboard/landing-pages/route'
import { Route as DashboardLandingPagesIndexRouteImport } from './routes/dashboard/landing-pages/index'
import { Route as DashboardAuditLogsIndexRouteImport } from './routes/dashboard/audit-logs/index'
import { Route as DashboardLandingPagesPageIdRouteImport } from './routes/dashboard/landing-pages/$pageId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentRoute = EnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactAdminRoute = ContactAdminRouteImport.update({
  id: '/contact-admin',
  path: '/contact-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/doctor/appointments',
  path: '/doctor/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantsRoute = DashboardTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGlobalStateRoute = DashboardGlobalStateRouteImport.update({
  id: '/global-state',
  path: '/global-state',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFormsRoute = DashboardFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDialogRoute = DashboardDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDataRoute = DashboardDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AppointmentsSelectTenantRoute =
  AppointmentsSelectTenantRouteImport.update({
    id: '/appointments/select-tenant',
    path: '/appointments/select-tenant',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentsMyRoute = AppointmentsMyRouteImport.update({
  id: '/appointments/my',
  path: '/appointments/my',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsConfirmationRoute =
  AppointmentsConfirmationRouteImport.update({
    id: '/appointments/confirmation',
    path: '/appointments/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppointmentsBookRoute = AppointmentsBookRouteImport.update({
  id: '/appointments/book',
  path: '/appointments/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsAppointmentIdRoute =
  AppointmentsAppointmentIdRouteImport.update({
    id: '/appointments/$appointmentId',
    path: '/appointments/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardLandingPagesRouteRoute =
  DashboardLandingPagesRouteRouteImport.update({
    id: '/landing-pages',
    path: '/landing-pages',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLandingPagesIndexRoute =
  DashboardLandingPagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLandingPagesRouteRoute,
  } as any)
const DashboardAuditLogsIndexRoute = DashboardAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLandingPagesPageIdRoute =
  DashboardLandingPagesPageIdRouteImport.update({
    id: '/$pageId',
    path: '/$pageId',
    getParentRoute: () => DashboardLandingPagesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/contact-admin': typeof ContactAdminRoute
  '/enrollment': typeof EnrollmentRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/landing-pages': typeof DashboardLandingPagesRouteRouteWithChildren
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/appointments/confirmation': typeof AppointmentsConfirmationRoute
  '/appointments/my': typeof AppointmentsMyRoute
  '/appointments/select-tenant': typeof AppointmentsSelectTenantRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/dialog': typeof DashboardDialogRoute
  '/dashboard/forms': typeof DashboardFormsRoute
  '/dashboard/global-state': typeof DashboardGlobalStateRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/landing-pages/$pageId': typeof DashboardLandingPagesPageIdRoute
  '/dashboard/audit-logs/': typeof DashboardAuditLogsIndexRoute
  '/dashboard/landing-pages/': typeof DashboardLandingPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-admin': typeof ContactAdminRoute
  '/enrollment': typeof EnrollmentRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/appointments/confirmation': typeof AppointmentsConfirmationRoute
  '/appointments/my': typeof AppointmentsMyRoute
  '/appointments/select-tenant': typeof AppointmentsSelectTenantRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/dialog': typeof DashboardDialogRoute
  '/dashboard/forms': typeof DashboardFormsRoute
  '/dashboard/global-state': typeof DashboardGlobalStateRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/landing-pages/$pageId': typeof DashboardLandingPagesPageIdRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsIndexRoute
  '/dashboard/landing-pages': typeof DashboardLandingPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/contact-admin': typeof ContactAdminRoute
  '/enrollment': typeof EnrollmentRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/landing-pages': typeof DashboardLandingPagesRouteRouteWithChildren
  '/appointments/$appointmentId': typeof AppointmentsAppointmentIdRoute
  '/appointments/book': typeof AppointmentsBookRoute
  '/appointments/confirmation': typeof AppointmentsConfirmationRoute
  '/appointments/my': typeof AppointmentsMyRoute
  '/appointments/select-tenant': typeof AppointmentsSelectTenantRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/dialog': typeof DashboardDialogRoute
  '/dashboard/forms': typeof DashboardFormsRoute
  '/dashboard/global-state': typeof DashboardGlobalStateRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/landing-pages/$pageId': typeof DashboardLandingPagesPageIdRoute
  '/dashboard/audit-logs/': typeof DashboardAuditLogsIndexRoute
  '/dashboard/landing-pages/': typeof DashboardLandingPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/contact-admin'
    | '/enrollment'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/dashboard/landing-pages'
    | '/appointments/$appointmentId'
    | '/appointments/book'
    | '/appointments/confirmation'
    | '/appointments/my'
    | '/appointments/select-tenant'
    | '/dashboard/appointments'
    | '/dashboard/data'
    | '/dashboard/dialog'
    | '/dashboard/forms'
    | '/dashboard/global-state'
    | '/dashboard/roles'
    | '/dashboard/tenants'
    | '/doctor/appointments'
    | '/dashboard/'
    | '/dashboard/landing-pages/$pageId'
    | '/dashboard/audit-logs/'
    | '/dashboard/landing-pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-admin'
    | '/enrollment'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/appointments/$appointmentId'
    | '/appointments/book'
    | '/appointments/confirmation'
    | '/appointments/my'
    | '/appointments/select-tenant'
    | '/dashboard/appointments'
    | '/dashboard/data'
    | '/dashboard/dialog'
    | '/dashboard/forms'
    | '/dashboard/global-state'
    | '/dashboard/roles'
    | '/dashboard/tenants'
    | '/doctor/appointments'
    | '/dashboard'
    | '/dashboard/landing-pages/$pageId'
    | '/dashboard/audit-logs'
    | '/dashboard/landing-pages'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/contact-admin'
    | '/enrollment'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/dashboard/landing-pages'
    | '/appointments/$appointmentId'
    | '/appointments/book'
    | '/appointments/confirmation'
    | '/appointments/my'
    | '/appointments/select-tenant'
    | '/dashboard/appointments'
    | '/dashboard/data'
    | '/dashboard/dialog'
    | '/dashboard/forms'
    | '/dashboard/global-state'
    | '/dashboard/roles'
    | '/dashboard/tenants'
    | '/doctor/appointments'
    | '/dashboard/'
    | '/dashboard/landing-pages/$pageId'
    | '/dashboard/audit-logs/'
    | '/dashboard/landing-pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ContactAdminRoute: typeof ContactAdminRoute
  EnrollmentRoute: typeof EnrollmentRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AppointmentsAppointmentIdRoute: typeof AppointmentsAppointmentIdRoute
  AppointmentsBookRoute: typeof AppointmentsBookRoute
  AppointmentsConfirmationRoute: typeof AppointmentsConfirmationRoute
  AppointmentsMyRoute: typeof AppointmentsMyRoute
  AppointmentsSelectTenantRoute: typeof AppointmentsSelectTenantRoute
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment': {
      id: '/enrollment'
      path: '/enrollment'
      fullPath: '/enrollment'
      preLoaderRoute: typeof EnrollmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-admin': {
      id: '/contact-admin'
      path: '/contact-admin'
      fullPath: '/contact-admin'
      preLoaderRoute: typeof ContactAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenants': {
      id: '/dashboard/tenants'
      path: '/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/global-state': {
      id: '/dashboard/global-state'
      path: '/global-state'
      fullPath: '/dashboard/global-state'
      preLoaderRoute: typeof DashboardGlobalStateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/forms': {
      id: '/dashboard/forms'
      path: '/forms'
      fullPath: '/dashboard/forms'
      preLoaderRoute: typeof DashboardFormsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/dialog': {
      id: '/dashboard/dialog'
      path: '/dialog'
      fullPath: '/dashboard/dialog'
      preLoaderRoute: typeof DashboardDialogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/data': {
      id: '/dashboard/data'
      path: '/data'
      fullPath: '/dashboard/data'
      preLoaderRoute: typeof DashboardDataRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/appointments/select-tenant': {
      id: '/appointments/select-tenant'
      path: '/appointments/select-tenant'
      fullPath: '/appointments/select-tenant'
      preLoaderRoute: typeof AppointmentsSelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/my': {
      id: '/appointments/my'
      path: '/appointments/my'
      fullPath: '/appointments/my'
      preLoaderRoute: typeof AppointmentsMyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/confirmation': {
      id: '/appointments/confirmation'
      path: '/appointments/confirmation'
      fullPath: '/appointments/confirmation'
      preLoaderRoute: typeof AppointmentsConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/book': {
      id: '/appointments/book'
      path: '/appointments/book'
      fullPath: '/appointments/book'
      preLoaderRoute: typeof AppointmentsBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$appointmentId': {
      id: '/appointments/$appointmentId'
      path: '/appointments/$appointmentId'
      fullPath: '/appointments/$appointmentId'
      preLoaderRoute: typeof AppointmentsAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/landing-pages': {
      id: '/dashboard/landing-pages'
      path: '/landing-pages'
      fullPath: '/dashboard/landing-pages'
      preLoaderRoute: typeof DashboardLandingPagesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/landing-pages/': {
      id: '/dashboard/landing-pages/'
      path: '/'
      fullPath: '/dashboard/landing-pages/'
      preLoaderRoute: typeof DashboardLandingPagesIndexRouteImport
      parentRoute: typeof DashboardLandingPagesRouteRoute
    }
    '/dashboard/audit-logs/': {
      id: '/dashboard/audit-logs/'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs/'
      preLoaderRoute: typeof DashboardAuditLogsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/landing-pages/$pageId': {
      id: '/dashboard/landing-pages/$pageId'
      path: '/$pageId'
      fullPath: '/dashboard/landing-pages/$pageId'
      preLoaderRoute: typeof DashboardLandingPagesPageIdRouteImport
      parentRoute: typeof DashboardLandingPagesRouteRoute
    }
  }
}

interface DashboardLandingPagesRouteRouteChildren {
  DashboardLandingPagesPageIdRoute: typeof DashboardLandingPagesPageIdRoute
  DashboardLandingPagesIndexRoute: typeof DashboardLandingPagesIndexRoute
}

const DashboardLandingPagesRouteRouteChildren: DashboardLandingPagesRouteRouteChildren =
  {
    DashboardLandingPagesPageIdRoute: DashboardLandingPagesPageIdRoute,
    DashboardLandingPagesIndexRoute: DashboardLandingPagesIndexRoute,
  }

const DashboardLandingPagesRouteRouteWithChildren =
  DashboardLandingPagesRouteRoute._addFileChildren(
    DashboardLandingPagesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardLandingPagesRouteRoute: typeof DashboardLandingPagesRouteRouteWithChildren
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardDataRoute: typeof DashboardDataRoute
  DashboardDialogRoute: typeof DashboardDialogRoute
  DashboardFormsRoute: typeof DashboardFormsRoute
  DashboardGlobalStateRoute: typeof DashboardGlobalStateRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardTenantsRoute: typeof DashboardTenantsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAuditLogsIndexRoute: typeof DashboardAuditLogsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLandingPagesRouteRoute: DashboardLandingPagesRouteRouteWithChildren,
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardDataRoute: DashboardDataRoute,
  DashboardDialogRoute: DashboardDialogRoute,
  DashboardFormsRoute: DashboardFormsRoute,
  DashboardGlobalStateRoute: DashboardGlobalStateRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardTenantsRoute: DashboardTenantsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAuditLogsIndexRoute: DashboardAuditLogsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ContactAdminRoute: ContactAdminRoute,
  EnrollmentRoute: EnrollmentRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AppointmentsAppointmentIdRoute: AppointmentsAppointmentIdRoute,
  AppointmentsBookRoute: AppointmentsBookRoute,
  AppointmentsConfirmationRoute: AppointmentsConfirmationRoute,
  AppointmentsMyRoute: AppointmentsMyRoute,
  AppointmentsSelectTenantRoute: AppointmentsSelectTenantRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
