/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTenantsRouteImport } from './routes/dashboard/tenants'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardGlobalStateRouteImport } from './routes/dashboard/global-state'
import { Route as DashboardFormsRouteImport } from './routes/dashboard/forms'
import { Route as DashboardDialogRouteImport } from './routes/dashboard/dialog'
import { Route as DashboardDataRouteImport } from './routes/dashboard/data'
import { Route as DashboardLandingPagesRouteRouteImport } from './routes/dashboard/landing-pages/route'
import { Route as DashboardLandingPagesIndexRouteImport } from './routes/dashboard/landing-pages/index'
import { Route as DashboardAuditLogsIndexRouteImport } from './routes/dashboard/audit-logs/index'
import { Route as DashboardLandingPagesPageIdRouteImport } from './routes/dashboard/landing-pages/$pageId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTenantsRoute = DashboardTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardGlobalStateRoute = DashboardGlobalStateRouteImport.update({
  id: '/global-state',
  path: '/global-state',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFormsRoute = DashboardFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDialogRoute = DashboardDialogRouteImport.update({
  id: '/dialog',
  path: '/dialog',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDataRoute = DashboardDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLandingPagesRouteRoute =
  DashboardLandingPagesRouteRouteImport.update({
    id: '/landing-pages',
    path: '/landing-pages',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLandingPagesIndexRoute =
  DashboardLandingPagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardLandingPagesRouteRoute,
  } as any)
const DashboardAuditLogsIndexRoute = DashboardAuditLogsIndexRouteImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLandingPagesPageIdRoute =
  DashboardLandingPagesPageIdRouteImport.update({
    id: '/$pageId',
    path: '/$pageId',
    getParentRoute: () => DashboardLandingPagesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/landing-pages': typeof DashboardLandingPagesRouteRouteWithChildren
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/dialog': typeof DashboardDialogRoute
  '/dashboard/forms': typeof DashboardFormsRoute
  '/dashboard/global-state': typeof DashboardGlobalStateRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/landing-pages/$pageId': typeof DashboardLandingPagesPageIdRoute
  '/dashboard/audit-logs/': typeof DashboardAuditLogsIndexRoute
  '/dashboard/landing-pages/': typeof DashboardLandingPagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/dialog': typeof DashboardDialogRoute
  '/dashboard/forms': typeof DashboardFormsRoute
  '/dashboard/global-state': typeof DashboardGlobalStateRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/landing-pages/$pageId': typeof DashboardLandingPagesPageIdRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsIndexRoute
  '/dashboard/landing-pages': typeof DashboardLandingPagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard/landing-pages': typeof DashboardLandingPagesRouteRouteWithChildren
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/dialog': typeof DashboardDialogRoute
  '/dashboard/forms': typeof DashboardFormsRoute
  '/dashboard/global-state': typeof DashboardGlobalStateRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/tenants': typeof DashboardTenantsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/landing-pages/$pageId': typeof DashboardLandingPagesPageIdRoute
  '/dashboard/audit-logs/': typeof DashboardAuditLogsIndexRoute
  '/dashboard/landing-pages/': typeof DashboardLandingPagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/dashboard/landing-pages'
    | '/dashboard/data'
    | '/dashboard/dialog'
    | '/dashboard/forms'
    | '/dashboard/global-state'
    | '/dashboard/roles'
    | '/dashboard/tenants'
    | '/dashboard/'
    | '/dashboard/landing-pages/$pageId'
    | '/dashboard/audit-logs/'
    | '/dashboard/landing-pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/dashboard/data'
    | '/dashboard/dialog'
    | '/dashboard/forms'
    | '/dashboard/global-state'
    | '/dashboard/roles'
    | '/dashboard/tenants'
    | '/dashboard'
    | '/dashboard/landing-pages/$pageId'
    | '/dashboard/audit-logs'
    | '/dashboard/landing-pages'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/dashboard/landing-pages'
    | '/dashboard/data'
    | '/dashboard/dialog'
    | '/dashboard/forms'
    | '/dashboard/global-state'
    | '/dashboard/roles'
    | '/dashboard/tenants'
    | '/dashboard/'
    | '/dashboard/landing-pages/$pageId'
    | '/dashboard/audit-logs/'
    | '/dashboard/landing-pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenants': {
      id: '/dashboard/tenants'
      path: '/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/global-state': {
      id: '/dashboard/global-state'
      path: '/global-state'
      fullPath: '/dashboard/global-state'
      preLoaderRoute: typeof DashboardGlobalStateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/forms': {
      id: '/dashboard/forms'
      path: '/forms'
      fullPath: '/dashboard/forms'
      preLoaderRoute: typeof DashboardFormsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/dialog': {
      id: '/dashboard/dialog'
      path: '/dialog'
      fullPath: '/dashboard/dialog'
      preLoaderRoute: typeof DashboardDialogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/data': {
      id: '/dashboard/data'
      path: '/data'
      fullPath: '/dashboard/data'
      preLoaderRoute: typeof DashboardDataRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/landing-pages': {
      id: '/dashboard/landing-pages'
      path: '/landing-pages'
      fullPath: '/dashboard/landing-pages'
      preLoaderRoute: typeof DashboardLandingPagesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/landing-pages/': {
      id: '/dashboard/landing-pages/'
      path: '/'
      fullPath: '/dashboard/landing-pages/'
      preLoaderRoute: typeof DashboardLandingPagesIndexRouteImport
      parentRoute: typeof DashboardLandingPagesRouteRoute
    }
    '/dashboard/audit-logs/': {
      id: '/dashboard/audit-logs/'
      path: '/audit-logs'
      fullPath: '/dashboard/audit-logs/'
      preLoaderRoute: typeof DashboardAuditLogsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/landing-pages/$pageId': {
      id: '/dashboard/landing-pages/$pageId'
      path: '/$pageId'
      fullPath: '/dashboard/landing-pages/$pageId'
      preLoaderRoute: typeof DashboardLandingPagesPageIdRouteImport
      parentRoute: typeof DashboardLandingPagesRouteRoute
    }
  }
}

interface DashboardLandingPagesRouteRouteChildren {
  DashboardLandingPagesPageIdRoute: typeof DashboardLandingPagesPageIdRoute
  DashboardLandingPagesIndexRoute: typeof DashboardLandingPagesIndexRoute
}

const DashboardLandingPagesRouteRouteChildren: DashboardLandingPagesRouteRouteChildren =
  {
    DashboardLandingPagesPageIdRoute: DashboardLandingPagesPageIdRoute,
    DashboardLandingPagesIndexRoute: DashboardLandingPagesIndexRoute,
  }

const DashboardLandingPagesRouteRouteWithChildren =
  DashboardLandingPagesRouteRoute._addFileChildren(
    DashboardLandingPagesRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardLandingPagesRouteRoute: typeof DashboardLandingPagesRouteRouteWithChildren
  DashboardDataRoute: typeof DashboardDataRoute
  DashboardDialogRoute: typeof DashboardDialogRoute
  DashboardFormsRoute: typeof DashboardFormsRoute
  DashboardGlobalStateRoute: typeof DashboardGlobalStateRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardTenantsRoute: typeof DashboardTenantsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAuditLogsIndexRoute: typeof DashboardAuditLogsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardLandingPagesRouteRoute: DashboardLandingPagesRouteRouteWithChildren,
  DashboardDataRoute: DashboardDataRoute,
  DashboardDialogRoute: DashboardDialogRoute,
  DashboardFormsRoute: DashboardFormsRoute,
  DashboardGlobalStateRoute: DashboardGlobalStateRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardTenantsRoute: DashboardTenantsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAuditLogsIndexRoute: DashboardAuditLogsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
