"""fix appointment table

Revision ID: 31c57f34f7d7
Revises: d3be20552ba7
Create Date: 2026-02-26 17:01:13.437618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c57f34f7d7'
down_revision: Union[str, Sequence[str], None] = 'd3be20552ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('appointments_patient_user_id_fkey', 'appointments', type_='foreignkey')
    op.create_foreign_key('fk_appointments_patient_tenant_user', 'appointments', 'patients', ['tenant_id', 'patient_user_id'], ['tenant_id', 'user_id'])
    op.drop_column('appointments', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_appointments_patient_tenant_user', 'appointments', type_='foreignkey')
    op.create_foreign_key('appointments_patient_user_id_fkey', 'appointments', 'patients', ['patient_user_id'], ['user_id'])
    # ### end Alembic commands ###
