"""fix patient table

Revision ID: d3be20552ba7
Revises: f6ccdf8dcc2a
Create Date: 2026-02-26 16:58:49.677968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3be20552ba7'
down_revision: Union[str, Sequence[str], None] = 'f6ccdf8dcc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('patients', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_patients_tenant_user', 'patients', ['tenant_id', 'user_id'])
    op.create_foreign_key(None, 'patients', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint('uq_patients_tenant_user', 'patients', type_='unique')
    op.drop_column('patients', 'tenant_id')
    op.drop_column('appointments', 'duration_minutes')
    # ### end Alembic commands ###
